version: '3.8'
services:
  app:
    image: serversideup/php:latest
    container_name: slimphp_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: ["php", "-S", "0.0.0.0:8080", "-t", "public"]
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: slimphp_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: slimphp_db
    ports:
      - "5432:5432"